data:
  type: image
  train_dir: data/cryptokitty
  test_dir: data/test
  lsun_categories_train: [bedroom_train]
  lsun_categories_test: [bedroom_test]
  img_size: 128
  nlabels: 1
generator:
  name: resnet
  kwargs:
    nfilter: 16
    nfilter_max: 512
    embed_size: 1
discriminator:
  name: resnet
  kwargs:
    nfilter: 16
    nfilter_max: 512
    embed_size: 1
z_dist:
  type: gauss
  dim: 256
training:
  out_dir: output/cryptokitty-256
  gan_type: standard
  reg_type: real
  reg_param: 10.
  batch_size: 24
  nworkers: 16
  take_model_average: true
  model_average_beta: 0.999
  model_average_reinit: false
  monitoring: tensorboard
  sample_every: 250
  sample_nlabels: 20
  inception_every: -1
  save_every: 900
  backup_every: 50000
  restart_every: -1
  optimizer: rmsprop
  lr_g: 0.0001
  lr_d: 0.0001
  lr_anneal: 1.
  lr_anneal_every: 150000
  d_steps: 1
  equalize_lr: false
test:
  batch_size: 4
  sample_size: 6
  sample_nrow: 3
  use_model_average: true
  compute_inception: false
  conditional_samples: false
interpolations:
  nzs: 10
  nsubsteps: 75
